### ISSUE TITLE
Erhalt von Mathjax bei Bionic Reading

### ISSUE THREAD

**Issue by tbez** [ProjektAnkiBVMD/notetype-addon#4]
Aktuell, versucht Bionic Reading, die selben Modifikationen die es auf Text anwendet, auch auf Mathjax Elemente anzuwenden. Dadurch wird aber das Mathjax-Element gestört. Wäre die Einführung eines Schutzes solcher Bausteine möglich?

**Comment by ProjektAnki** [comment]
Wahrscheinlich ja. Der Code stammt allerdings nicht aus unserer Feder, sondern ist modifiziert vom entsprechenden AnKing-AddOn: https://github.com/AnKing-VIP/anki-bionic-reading
Ergo am Besten dort ein Issue eröffnen 😄👍
