### ISSUE TITLE
Blickdiagnosen funktionieren nicht

### ISSUE THREAD

**Issue by ruellmannlauch** [ProjektAnkiBVMD/notetype-addon#6]
Hi, bei mir funktionieren die Blickdiagnosen nicht - es wird die Karte angezeigt, aber nicht das Bild, auch schon in der Kartenverwaltung. Ich hab schon einmal alle Notiztypen geresettet, aber das hat nichts gebracht. Wäre klasse wenn ihr weiterhelfen könnt
!
![image](https://github.com/ProjektAnkiBVMD/notetype-addon/assets/173778929/b1ea49c2-4b7d-4bc3-b250-a4722c8faf64)

![image](https://github.com/ProjektAnkiBVMD/notetype-addon/assets/173778929/418b4e01-f491-4798-8e33-ab3e00b8c3ae)

**Comment by ProjektAnki** [comment]
Schau mal aufm [Discord-Server](https://discord.com/invite/5DMsDg8Rvu), da kann dir konkret mit Medien-Fragen weitergeholfen werden 😄
