### ISSUE TITLE
Please enable scrolling with arrow key

### ISSUE THREAD

**Issue by CTRossler** [ProjektAnkiBVMD/notetype-addon#7]
I'm not able to use the arrow keys to scroll a card like the following using the arrow keys. It would be very helpful to me since I am using a remote to learn with anki.
<img width="957" alt="image" src="https://github.com/user-attachments/assets/1e47f398-537f-46e9-af18-f055d685cb56">

**Comment by ProjektAnki** [comment]
Hi @CTRossler,
sorry for the late reply.

This is a known "issue", and this incompatibility is in-and-of-itself intended.
Obviously not intended to disadvantage controller users, however, it is a conscious design choice to keep general elements of the notetype seperately scrollable. This unfortunately interferes with the way that most add-ons that enable scrolling support (via controller / vim-like keybindings etc.) work.

BUuuuut do not despair, I've put an easy to use "fix" on our wiki page → [ADD-ON — SCHNIPSEL FÜR ADVANCED STYLING: Mit Controller scrollen](https://www.ankizin.de/wiki/add-on-schnipsel-fuer-advanced-styling/#controller-scrolling)

Best
